# Generated by scripts/generate-contracts.mjs. Do not edit.
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

class AgentState(str, Enum):
    IDLE = "idle"
    LISTENING = "listening"
    RECOGNIZING = "recognizing"
    THINKING = "thinking"
    CONFIRMING = "confirming"
    ACTING = "acting"
    SPEAKING = "speaking"
    ERROR = "error"

class AgentEventType(str, Enum):
    CLIENT_MESSAGE = "client.message"
    AGENT_STATE = "agent.state"
    ASSISTANT_DELTA = "assistant.delta"
    ASSISTANT_MESSAGE = "assistant.message"
    TOOL_CONFIRMATION_REQUIRED = "tool.confirmation_required"
    TOOL_RESULT = "tool.result"
    REQUEST_CANCEL = "request.cancel"
    REQUEST_CANCELLED = "request.cancelled"
    DIAGNOSTICS_ECHO_REQUEST = "diagnostics.echo.request"
    DIAGNOSTICS_ECHO_RESPONSE = "diagnostics.echo.response"
    BACKEND_STATUS = "backend.status"
    ERROR = "error"

class ToolRiskLevel(str, Enum):
    L0 = "L0"
    L1 = "L1"
    L2 = "L2"
    L3 = "L3"

class AgentEvent(BaseModel):
    type: AgentEventType
    version: str = Field(pattern=r"^1\.0$")
    session_id: str
    request_id: str
    timestamp: str
    data: dict[str, Any]

class AgentError(BaseModel):
    error_code: str
    message: str
    recoverable: bool
    request_id: str
    details: dict[str, Any] | None = None
